### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#1060]
Report from user received by email:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getrandom" referenced by "/data/app/org.ergvein.wallet-1/split_config.arm64_v8a.apk!/lib/arm64-v8a/libHaskellActivity.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1530)
	at systems.obsidian.HaskellActivity.<clinit>(HaskellActivity.java:40)
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6358)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
```

**Comment by NCrashed** [comment]
Found that android version with a kernel older than 3.17 doesn't support getrandom syscall.

**Comment by NCrashed** [comment]
Android 5 Lollipop runs kernel 3.16.1. The issue is more likely occurred at 22 API level that we doesn't support.
